FROM mcr.microsoft.com/devcontainers/python:3.11-bullseye

# Install Jupyter Notebook
RUN pip install --upgrade pip && \
    pip install notebook

# [Optional] Install additional Python packages here
# RUN pip install pandas matplotlib